### ISSUE TITLE
jquery conflict?

### ISSUE THREAD

**Issue by ricardo-vargas** [livecomposer/Live-Composer#10]
I am getting this error in wordpress when activating editor and it doesn't let you work.

```
Uncaught TypeError: jQuery(...).jScrollPane is not a function
(anonymous function)	@	builder.main.min.js?ver=1.0.6.1:3
j	@	jquery.js?ver=1.11.3:2
k.fireWith	@	jquery.js?ver=1.11.3:2
m.extend.ready	@	jquery.js?ver=1.11.3:2
J
```

I fixed it by removing jquery enqueue from the theme Im using it with.

**Comment by livecomposer** [comment]
In what way did the theme include jQuery? Was it the regular way:

`wp_enqueue_script('jquery')`

Or perhaps directly with a script HTML tag? If it was like that then 2 version of jQuery were being loaded and that would cause issues.

**Comment by ricardo-vargas** [comment]
Thanks for your answer, yes it was via
    wp_enqueue_script('jquery')
I solved it by removing that call... perhaps there should be an option to not include jquery in the plugin? like a conflict mode.
