### ISSUE TITLE
Option to set nofollow for the links

### ISSUE THREAD

**Issue by xtiger15x** [livecomposer/Live-Composer#11]
I'm a php developer in Lumberman Designs company and have two questions.

1) Our customers need an option to put rel = "nofollow" for button and infobox modules. We can change these modules ourself, but want to ask if you can add this option by default?
2) If you add a check box control to any module - https://www.evernote.com/shard/s554/sh/f23c2c6e-879b-480e-9992-d5f5d9f409ef/2574a887bc01877e it will not appear  - https://www.evernote.com/shard/s554/sh/18729944-df49-4cc5-8163-19925b941ef7/dd2507d68c263ce0
untill there are two checkboxes - https://www.evernote.com/shard/s554/sh/84223585-2ff0-45a7-be4b-efa9bf6f67d0/7c91ec73c0cb1b80
Can you please make posible to have a single checkbox?

Thank you!

**Comment by lumberman** [comment]
@WPCanyon any updates on this? 

Can we do the code change a propose a push request to make it done?

**Comment by livecomposer** [comment]
Hi Vlad,

If you have the code ready make a push request and I'll approve. If not I'll try to have it done for the next update.

**Comment by lumberman** [comment]
No we have no code for this yet, but I'm not sure if you want to have it among the module settings?

**Comment by livecomposer** [comment]
Well it's a simple one so no harm in having it in the settings and it's a valuable option to have.

**Comment by WPCanyon** [comment]
Was also just contacted by a user asking about this, so definetely a valuable option to have.

**Comment by philamery** [comment]
@lumberman @livecomposer 
hi, 
looks like this feature hasn't been implemented yet in Live Composer 
till now I used Ultimate Nofollow plugin but it would be definitely advantageous to have it included within Live Composer especially for the simple reason it doesn't look to be a major task 
hope our voice will get heared and some further steps will be taken to overcome this obstacle  

thanks in advance and looking forward to your feedback
