### ISSUE TITLE
Scroll list of modules with a mouse wheel.

### ISSUE THREAD

**Issue by mozalan** [livecomposer/Live-Composer#111]
Only works when first time Activator is loaded, it stops working once changes are confirmed and published or if you would change category of elements from the left - bottom corner. Just tried on **Version 10.9.29** - thanks in advance.

**P.S**. Some people might not use mouse wheels but most people that I work with do use mouse wheels a lot and it saves time.

**Comment by livecomposer** [comment]
@mozalan Can you please check this functionality again?

**Comment by mozalan** [comment]
Tried, still the same I'm afraid.. it works only on first wheel scroll then stops and wouldn't respond. Tried on every major browser to no avail.

**Comment by mozalan** [comment]
Works beautifully now :) Many thanks!
