### ISSUE TITLE
JS Syntax error

### ISSUE THREAD

**Issue by mozalan** [livecomposer/Live-Composer#122]
Uncaught Error: Syntax error, unrecognized expression: [href=#] in file "http://www.example.com/wp-includes/js/jquery/jquery.js?ver=1.12.4" on line 2, char 12727

**Comment by mozalan** [comment]
Live Composer 1.0.9.39 - mouse scroll still doesn't work, not been fixed I'm afraid.

**Comment by livecomposer** [comment]
@mozalan Can you please check our latest version. It should be working now. 
Please, let me know if scrolling 'feels' comfortable (good speed)?

Thank you.

**Comment by livecomposer** [comment]
#111
