### ISSUE TITLE
Does "Comments Reply" and "Nested Comments" work by default?

### ISSUE THREAD

**Issue by lumberman** [livecomposer/Live-Composer#13]
Hi Slobodan,

Can't get "Comments Reply" and "Nested Comments" functionality to work properly in my theme, so decided to ask if it works by default?

Thank you!

**Comment by livecomposer** [comment]
Replies and nested comments definetely work, with all the themes when making demo content I always made nested comments and used comments reply.

You had a dev/testing install of SEOWP set up, not sure if you still do and I can't find the info in the emails, can you send it over to my email and I'll test out and see what's going on.

**Comment by lumberman** [comment]
For some reason, the parent ID does not pass to the COMMENT FORM module. I do think it caused my renamed comment ID's. [This function](https://github.com/WordPress/WordPress/blob/f1d0763785466d533cf70414c2c3dcc9a1eb2d47/wp-includes/js/comment-reply.js) get the comment block by ID. I will double check with LC installed on default/blank theme and report back.

Thank you!

**Comment by livecomposer** [comment]
Do you have some JS code in there which stops links from going to their URL if they have # in it and instead slide to the element with the ID?
