### ISSUE TITLE
Can Only Use 2 Templates

### ISSUE THREAD

**Issue by Deanphillips** [livecomposer/Live-Composer#131]
Since switching to the latest LC I can only have 2 blog post templates, unlike before, can we please get this changed back Vlad Mitkovsky?

I had 3 templates:

- Default blog

- Guide like blog post

- Landing page like blog post

Just discovered this, and some of my posts aren't working now because of it.

Dean

P.S I've just switched back to Version 1.0.9.38 so I could get these back (for now)

**Comment by livecomposer** [comment]
Thanks for rerooting this Dean,
I will check it today and hopefully fix it.

What are your thoughts on new location for LC templates and the way template options changed?

**Comment by Deanphillips** [comment]
I really like it :)

**Comment by livecomposer** [comment]
Dean, can you please check this version: 
https://codeload.github.com/livecomposer/Live-Composer/zip/issue/131

**Comment by Deanphillips** [comment]
That feature works now, man

**Comment by Deanphillips** [comment]
Issue with that version:

ZERO responsiveness (enabled doesn't work) :)

**Comment by livecomposer** [comment]
Yes, responsiveness fixed in another branch. 
I merged both bug fixed with master.

https://github.com/livecomposer/Live-Composer/archive/master.zip
