### ISSUE TITLE
IE11 - Error

### ISSUE THREAD

**Issue by xdima92x** [livecomposer/Live-Composer#140]
Hi) If you will be to use this option:
1) **define( 'SCRIPT_DEBUG', true );** - https://www.evernote.com/shard/s554/sh/368052fd-1fed-4967-86ba-843b366ab743/c95b4998fb8f7256
2) **define( 'SCRIPT_DEBUG', false );** - https://www.evernote.com/shard/s554/sh/80f7ec5d-8c18-4563-85d9-240ffd10af2e/b46aca631d117626

**Comment by livecomposer** [comment]
@NGorco Please check this problem. I have no Windows installed.

**Comment by NGorco** [comment]
Problem in Sortable.js. It crashes everything.
