### ISSUE TITLE
Cannot open "WP Editor"

### ISSUE THREAD

**Issue by elfomaniac** [livecomposer/Live-Composer#153]
LC - v 1.0.9.44
WP - v4.6

Add Accordion but cannot edit text. A click on "Open in WP Editor" doesn't work.

**Comment by livecomposer** [comment]
builder.module.functions.js?ver=1.1:172 
Uncaught ReferenceError: dslc_accordion_generate_code is not defined

**Comment by livecomposer** [comment]
Fixed in version 1.1.1 published on WordPress.org. Please update via your WP Admin.
**THANK YOU** for help!
