### ISSUE TITLE
Widgets not loading

### ISSUE THREAD

**Issue by jessicahawkins3344** [livecomposer/Live-Composer#154]
The widgets module has stopped working for me, after updating as well. When I select which widget to use, it will not load it... and if you click on the settings cog again, it's like it isn't saving your selection from the dropdown menu of widgets.

**Comment by livecomposer** [comment]
Hi Jessica,
Thank you for reporting this problem. I can't reproduce this bug on my end. 

What name did you set for the Widget Area?
What happens if you add one more Widget Area in **WP Admin > Settings > Widgets Module**?

**Comment by jessicahawkins3344** [comment]
View this link... https://drive.google.com/file/d/0B7EQq0DFNDK-NzNoS0V4M1RLVVE/view

**Comment by livecomposer** [comment]
I can see that on video you have a small red bug icon next to the CONFIRM / CANCEL button. What does it say?

**Comment by livecomposer** [comment]
@jessicahawkins3344 any more info on this?
We don't get the same issue from any other users.
