### ISSUE TITLE
Modules Row Edit Menu Disappears after moving.

### ISSUE THREAD

**Issue by jessicahawkins3344** [livecomposer/Live-Composer#158]
With the new version, if you move one of your module rows, the edit menu on any module row will no longer display and you have to reload the page to get it to work again.

Also, the moving is much more difficult now then it was.... I could grab an module row, or element and scroll while holding easily. I can scroll with my mouse at the same time as holding a module or element anymore.

**Comment by livecomposer** [comment]
@NGorco let roll back to JQuery sortable for sections for now.

**Comment by livecomposer** [comment]
Fixed in version 1.1.1 published on WordPress.org. Please update via your WP Admin.
**THANK YOU** for help!
