### ISSUE TITLE
WP Editor does not format text

### ISSUE THREAD

**Issue by elfomaniac** [livecomposer/Live-Composer#168]
![wpeditor](https://cloud.githubusercontent.com/assets/9195541/17742661/f14ce8a0-646e-11e6-9341-fb8fbee40742.jpg)

**Comment by elfomaniac** [comment]
P.S LC v. 1.1.1
WP v. 4.6
In new version of the WP Editor were made some changes. Looks like Live Composer do not know about it.

**Comment by livecomposer** [comment]
Content for Accordion and Tabs supposed to be simple text. If you need more styling please add custom CSS for now. Most likely we will not change it's behavior as it can cause issues to the users who already use it. It the future we will create Accordion/Tabs PRO module were you will be able to drop any modules inside.

Thank you.
