### ISSUE TITLE
Bug: Red background on jspVerticalBar

### ISSUE THREAD

**Issue by michalkopanski** [livecomposer/Live-Composer#17]
When adding a textarea option to a module, a custom scrollbar appears that has incorrect styling.

![](http://kpnsk.me/fW99/Screen%20Shot%202016-03-26%20at%209.43.05%20AM.png)

`.jspVerticalBar` has a `background: red` when it should have no background at all.

**Comment by livecomposer** [comment]
Hi Michal,
We are working on a new UI for styling options panel, but this bug will be fixed in the coming update as well. 

Thank you for reporting it.

**Comment by michalkopanski** [comment]
@livecomposer can you link me to the commit/PR that fixes this issue?

**Comment by livecomposer** [comment]
@michalkopanski you are welcome to use the latest commit in the master branch. Unfortunately I can't find a commit that fix this particular issue as it was fixed and month or so ago.

**Comment by michalkopanski** [comment]
@livecomposer Great, thanks for the reply!
