### ISSUE TITLE
Staff Email leads to 404

### ISSUE THREAD

**Issue by jessicahawkins3344** [livecomposer/Live-Composer#173]
In the staff post types, there is an e-mail field... that logically should link to mailto:example@here.com... but it tries to link you to a page using their e-mail as a slug which obviously doesn't exist... this has been a long running issue thanks

**Comment by jessicahawkins3344** [comment]
Can close: just realized you have to enter the mailto: in the actual field

**Comment by livecomposer** [comment]
I'll think how we can improve UI to make it clear.
Thank you.
