### ISSUE TITLE
Version 1.1+ issue with post archive templates, styling is missing

### ISSUE THREAD

**Issue by BobaWebDev** [livecomposer/Live-Composer#186]
A customer of Josephine theme reported an issue today that the archive pages are not working, that's because the system how archive/search/404 is changed to work with the dslc_templates post type instead of pages. That's not a big problem, will release an update for the theme.

But the issue I ran into with the new system is that styling does not get applied to the modules. To ensure it's not a conflict with the theme I created a fresh install, running on TwentySixteen and the issue is still there.

The template:

![lc-template](https://cloud.githubusercontent.com/assets/4485586/17777851/4df68a2c-6562-11e6-9115-139b5bdc17b1.jpg)

Actual category archive

![lc-archive](https://cloud.githubusercontent.com/assets/4485586/17777885/65efd17e-6562-11e6-85b0-187ceed10066.jpg)

How to replicate:

1. Create a new template and set it to power blog post archives
2. Open it up in LC, add a text modle ( or any module ), change some styling options and publish changes

If you check the template directly the styling is applied. If you check an actual archive page there is no styling applied to the modules.

Also the URL for the "activate live composer" button when on the archive page is wrong, probably related to the missing styles, it doesn't know what styles to output and which URL should be for the button, so the logic in LC to figure out what's currently displayed is broken.  

But it's been a while since I worked on LC, I don't quite remember the code, so might be 2 separate causes of the issues.

**Comment by deptgraffig** [comment]
Great to hear from you Slobodan - hope all is going well

**Comment by elfomaniac** [comment]
Styling does not work on any post  
https://github.com/livecomposer/Live-Composer/issues/177

**Comment by livecomposer** [comment]
Hey Slobodan sorry for these issues.

Then you click to save the post options it will update the wp_options > 'dslc_plugin_options_archives' > 'post_archive' etc. 

I missed the posts archive issue in this case. Post template ID was saving under 'post_archive' but checking for 'post' while looking for template id on rendering.

We will roll out php and js automated testing soon, to kill bugs like this on development stage.
