### ISSUE TITLE
Does it work with any theme?

### ISSUE THREAD

**Issue by Shaz3e** [livecomposer/Live-Composer#19]
Hi there,

How does it work with any theme? I tried to copy functions.php into my theme folder and header/footer functions in my header/footer.php but it is not working can you please guide me if I am doing wrong?

Edited: Typo fixed.

**Comment by livecomposer** [comment]
Hi there,

I'm not sure I understand your question. Live Composer is a WordPress plugin that you install on your websites as any other plugin.

Please, describe your problem/question in more details and I will be happy to help.

**Comment by Shaz3e** [comment]
I want to use this plugin with my custom theme how can I use it?

**Comment by livecomposer** [comment]
Please, go to WP Admin > Plugins > Add New > Search > Live Composer and install it from there. We keep a copy on GitHub for development purposes.

Good luck with your project.
