### ISSUE TITLE
Global Icon Style in main.css

### ISSUE THREAD

**Issue by aman704** [livecomposer/Live-Composer#6]
Files:
/css/main.css
/css/main.min.css

In main.css line 58 #dslc-content i { font-style: italic; }
Any specific reason for this property? I've to always reset it using theme's CSS as it messes with the icons.

**Comment by livecomposer** [comment]
Not entirely sure when was that added. Most likely there was a support request about b and i not working so the CSS for them was added. strong and em are being used for a long time now so I don't think I added it at the beginning ( version 1.0 )

I'll get rid of it now ( 1.0.5 in a few hours ) and hopefully no issues arise.

**Comment by aman704** [comment]
Thanks
